/* Automatically generated nanopb header */
/* Generated by 0.4.1-dev */

#ifndef PB_PROTOLINK_PROTOBUF_PROTOLINK_PB_H_INCLUDED
#define PB_PROTOLINK_PROTOBUF_PROTOLINK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Result_ResultCode {
    Result_ResultCode_OK = 0,
    Result_ResultCode_ERROR = 1
} Result_ResultCode;

/* Struct definitions */
typedef struct _Result {
    pb_callback_t message;
} Result;

typedef struct _UpdateFB {
    pb_callback_t fb;
} UpdateFB;

typedef struct _Command {
    pb_callback_t cb_c;
    pb_size_t which_c;
    union {
        UpdateFB updatefb;
    } c;
} Command;


/* Helper constants for enums */
#define _Result_ResultCode_MIN Result_ResultCode_OK
#define _Result_ResultCode_MAX Result_ResultCode_ERROR
#define _Result_ResultCode_ARRAYSIZE ((Result_ResultCode)(Result_ResultCode_ERROR+1))


/* Initializer values for message structs */
#define Command_init_default                     {{{NULL}, NULL}, 0, {UpdateFB_init_default}}
#define UpdateFB_init_default                    {{{NULL}, NULL}}
#define Result_init_default                      {{{NULL}, NULL}}
#define Command_init_zero                        {{{NULL}, NULL}, 0, {UpdateFB_init_zero}}
#define UpdateFB_init_zero                       {{{NULL}, NULL}}
#define Result_init_zero                         {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Result_message_tag                       1
#define UpdateFB_fb_tag                          1
#define Command_updatefb_tag                     1

/* Struct field encoding specification for nanopb */
#define Command_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (c,updatefb,c.updatefb),   1)
#define Command_CALLBACK NULL
#define Command_DEFAULT NULL
#define Command_c_updatefb_MSGTYPE UpdateFB

#define UpdateFB_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    fb,                1)
#define UpdateFB_CALLBACK pb_default_field_callback
#define UpdateFB_DEFAULT NULL

#define Result_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   message,           1)
#define Result_CALLBACK pb_default_field_callback
#define Result_DEFAULT NULL

extern const pb_msgdesc_t Command_msg;
extern const pb_msgdesc_t UpdateFB_msg;
extern const pb_msgdesc_t Result_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Command_fields &Command_msg
#define UpdateFB_fields &UpdateFB_msg
#define Result_fields &Result_msg

/* Maximum encoded size of messages (where known) */
/* Command_size depends on runtime parameters */
/* UpdateFB_size depends on runtime parameters */
/* Result_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
